// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CssTools
{
    static class Vsix
    {
        public const string Id = "0020efc9-e999-4e6f-a2b6-604127f480bc";
        public const string Name = "CSS Tools";
        public const string Description = @"Provides additional features to the CSS editor in Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "css, less, sass, scss, stylesheet";
    }
}
